"""Backend Protocol interfaces. Every concrete backend (real Windows,
fake/test-double) implements these exactly. Tool executors in
services/local-api depend only on these Protocols, never on a concrete
backend class — see docs/phase-2/COMPUTER-CONTROL-DESIGN.md §3.
"""

from __future__ import annotations

from typing import Protocol

from computer_control.core.models import (
    ApplicationInfo,
    InputTarget,
    ProcessInfo,
    ScreenCaptureResult,
    UIElementInfo,
    WindowInfo,
)
from computer_control.core.selectors import UISelector


class ApplicationBackend(Protocol):
    async def list_running(self) -> list[ApplicationInfo]: ...
    async def find(self, query: str) -> list[ApplicationInfo]: ...
    async def launch(self, executable_path: str, args: list[str]) -> ApplicationInfo: ...
    async def focus(self, process_id: int) -> bool: ...
    async def is_running(self, process_id: int) -> bool: ...
    async def close(self, process_id: int) -> bool: ...


class WindowBackend(Protocol):
    async def list_windows(self) -> list[WindowInfo]: ...
    async def find_window(self, title_query: str) -> WindowInfo | None: ...
    async def get_window(self, handle: str) -> WindowInfo | None: ...
    async def focus_window(self, handle: str) -> bool: ...
    async def minimize(self, handle: str) -> bool: ...
    async def maximize(self, handle: str) -> bool: ...
    async def restore(self, handle: str) -> bool: ...
    async def close_window(self, handle: str) -> bool: ...
    async def get_active_window(self) -> WindowInfo | None: ...


class ProcessBackend(Protocol):
    async def list_processes(self) -> list[ProcessInfo]: ...
    async def find_process(self, name_query: str) -> list[ProcessInfo]: ...


class UIAutomationBackend(Protocol):
    async def find_element(
        self, selector: UISelector, timeout_seconds: float
    ) -> UIElementInfo | None: ...
    async def find_all(self, selector: UISelector) -> list[UIElementInfo]: ...
    async def click_element(self, selector: UISelector, timeout_seconds: float) -> bool: ...
    async def type_into_element(
        self, selector: UISelector, text: str, timeout_seconds: float
    ) -> bool: ...


class KeyboardBackend(Protocol):
    async def type_text(self, target: InputTarget, text: str) -> bool: ...
    async def press(self, target: InputTarget, key: str) -> bool: ...
    async def hotkey(self, target: InputTarget, keys: list[str]) -> bool: ...


class MouseBackend(Protocol):
    """Every method is selector-based (a semantic target that resolves to
    coordinates internally) — see docs/phase-2 §10. There is no
    coordinate-only method on this interface at all; raw coordinate
    clicking is a deliberately unimplemented last resort in Phase 2, not
    merely deprioritized — see docs/phase-2/INPUT-CONTROL.md."""

    async def move(self, selector: UISelector) -> bool: ...
    async def click(self, selector: UISelector) -> bool: ...
    async def double_click(self, selector: UISelector) -> bool: ...
    async def right_click(self, selector: UISelector) -> bool: ...
    async def scroll(self, selector: UISelector, amount: int) -> bool: ...


class ScreenBackend(Protocol):
    async def capture_full(self) -> ScreenCaptureResult: ...
    async def capture_window(self, handle: str) -> ScreenCaptureResult: ...
    async def capture_active_window(self) -> ScreenCaptureResult: ...
