"""initial schema

Revision ID: 51aedcfad492
Revises: 
Create Date: 2026-08-26 12:40:00.448205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51aedcfad492'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('executable_path', sa.String(length=1024), nullable=True),
    sa.Column('identifier', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('devices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('AC', 'FAN', 'TV', 'REFRIGERATOR', 'LIGHT', 'SMART_PLUG', 'SPEAKER', 'OTHER', name='devicetype'), nullable=False),
    sa.Column('trust_status', sa.Enum('UNPAIRED', 'PAIRING', 'PAIRED', 'REVOKED', name='devicetruststatus'), nullable=False),
    sa.Column('protocol', sa.Enum('MATTER', 'MQTT', 'LOCAL_HTTP', 'BLUETOOTH', 'VENDOR_API', name='connectionprotocol'), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('credentials_ref', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('credentials_ref', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('scope_key', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tools',
    sa.Column('tool_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.Enum('FILESYSTEM', 'WINDOWS', 'PROCESS', 'SCREEN', 'KEYBOARD', 'MOUSE', 'BROWSER', 'COMMUNICATION', 'MEDIA', 'DOCUMENTS', 'SYSTEM', 'IOT', name='toolcategory'), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('required_permission', sa.String(length=200), nullable=False),
    sa.Column('confirmation_policy', sa.Enum('NEVER', 'SESSION', 'ALWAYS', name='confirmationpolicy'), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('cancellable', sa.Boolean(), nullable=False),
    sa.Column('verification_strategy', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id')
    )
    op.create_table('users',
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('tool_id', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('target', sa.String(length=1000), nullable=True),
    sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('permission_grant_id', sa.String(length=64), nullable=True),
    sa.Column('request_payload_summary', sa.JSON(), nullable=False),
    sa.Column('result_status', sa.Enum('SUCCESS', 'FAILURE', 'TIMEOUT', 'CANCELLED', name='toolresultstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('evidence_tier_used', sa.Enum('NATIVE_API', 'UI_AUTOMATION', 'ACCESSIBILITY_TREE', 'APP_INTEGRATION', 'BROWSER_DOM', 'OCR', 'VISION_MODEL', 'COORDINATE', name='evidencetier'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_capabilities',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('capability_key', sa.String(length=200), nullable=False),
    sa.Column('value_schema', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_permissions',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('capability_key', sa.String(length=200), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('SHORT_TERM', 'CONVERSATION', 'TASK', 'USER_PREFERENCE', 'SEMANTIC', 'WORKFLOW', 'DEVICE', name='memorycategory'), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_grants',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(length=200), nullable=False),
    sa.Column('target', sa.String(length=1000), nullable=True),
    sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('scope', sa.Enum('ALLOW_ONCE', 'ALLOW_SESSION', 'ALWAYS_ALLOW', 'DENY', 'CANCEL', name='permissiondecision'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_phrase', sa.String(length=500), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=8000), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('state', sa.Enum('RECEIVED', 'UNDERSTANDING', 'PLANNING', 'WAITING_PERMISSION', 'EXECUTING', 'OBSERVING', 'VERIFYING', 'RECOVERING', 'WAITING_USER', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstate'), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    op.create_table('task_steps',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('RECEIVED', 'UNDERSTANDING', 'PLANNING', 'WAITING_PERMISSION', 'EXECUTING', 'OBSERVING', 'VERIFYING', 'RECOVERING', 'WAITING_USER', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstate'), nullable=False),
    sa.Column('tool_id', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_steps')
    op.drop_table('tasks')
    op.drop_table('messages')
    op.drop_table('workflows')
    op.drop_table('permission_grants')
    op.drop_table('memories')
    op.drop_table('device_permissions')
    op.drop_table('device_capabilities')
    op.drop_table('conversations')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('tools')
    op.drop_table('system_settings')
    op.drop_table('permissions')
    op.drop_table('integrations')
    op.drop_table('devices')
    op.drop_table('applications')
    # ### end Alembic commands ###
