"""phase 2: extend applications table for the application registry

Revision ID: 63d3d077887d
Revises: bdcb05c63501
Create Date: 2026-08-26 14:21:34.956216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d3d077887d'
down_revision: Union[str, None] = 'bdcb05c63501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('aliases', sa.JSON(), nullable=False))
    op.add_column('applications', sa.Column('executable_candidates', sa.JSON(), nullable=False))
    op.add_column('applications', sa.Column('publisher', sa.String(length=200), nullable=True))
    op.add_column('applications', sa.Column('install_source', sa.String(length=200), nullable=True))
    op.add_column('applications', sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=False))
    op.add_column('applications', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('verification_strategy', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'verification_strategy')
    op.drop_column('applications', 'enabled')
    op.drop_column('applications', 'risk_level')
    op.drop_column('applications', 'install_source')
    op.drop_column('applications', 'publisher')
    op.drop_column('applications', 'executable_candidates')
    op.drop_column('applications', 'aliases')
    # ### end Alembic commands ###
