"""phase 5: voice sessions table and task failure category

Adds the minimal `voice_sessions` table (docs/phase-5/
PHASE-5-IMPLEMENTATION-PLAN.md §8 — no raw audio, no transcript column)
and `tasks.failure_category`, so a real ErrorCategory survives past task
completion for ResponseGenerator to speak honestly from (brief §74-79).

Deliberately does NOT add the `parent_task_id` -> `tasks.id` foreign key
constraint autogenerate detected: this is the same pre-existing gap
de808f46a925 (Phase 4) already documented and intentionally left alone —
SQLite cannot ALTER a table to add a constraint without a batch-mode
rebuild, unnecessary risk for a nullable, self-referential column the ORM
layer already models. Not a Phase 5 concern to fix.

Revision ID: bffc0ab7b27f
Revises: de808f46a925
Create Date: 2026-08-26 18:25:25.627140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffc0ab7b27f'
down_revision: Union[str, None] = 'de808f46a925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_sessions',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.Enum('EN', 'TA', 'TA_EN', 'UNKNOWN', name='language'), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'WAKE_DETECTED', 'LISTENING', 'TRANSCRIBING', 'UNDERSTANDING', 'EXECUTING', 'RESPONDING', 'INTERRUPTED', 'ERROR', 'RECOVERY', 'ENDED', name='voicestate'), nullable=False),
    sa.Column('active_task_id', sa.String(), nullable=True),
    sa.Column('activation_source', sa.Enum('WAKE_WORD', 'PUSH_TO_TALK', 'HOTKEY', 'API', name='activationsource'), nullable=False),
    sa.Column('audio_device', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('failure_category', sa.Enum('VALIDATION_ERROR', 'PERMISSION_DENIED', 'AUTHENTICATION_REQUIRED', 'DEVICE_UNAVAILABLE', 'APPLICATION_NOT_FOUND', 'FILE_NOT_FOUND', 'UI_NOT_FOUND', 'NETWORK_ERROR', 'TIMEOUT', 'TOOL_FAILURE', 'MODEL_FAILURE', 'VISION_FAILURE', 'UNKNOWN_ERROR', 'APPLICATION_LAUNCH_FAILED', 'WINDOW_NOT_FOUND', 'WINDOW_NOT_ACTIVE', 'UI_ELEMENT_DISABLED', 'PATH_NOT_ALLOWED', 'PATH_PROTECTED', 'TARGET_CONTEXT_REQUIRED', 'INPUT_BLOCKED', 'VERIFICATION_FAILED', 'TOOL_DISABLED', 'OPERATION_CANCELLED', 'UNKNOWN_WINDOWS_ERROR', 'PLATFORM_NOT_SUPPORTED', 'AMBIGUOUS_TARGET', 'STATE_MISMATCH', 'RESOURCE_BUSY', 'INVALID_PLAN', 'UNKNOWN_TOOL', 'CAPABILITY_UNAVAILABLE', 'MIC_NOT_FOUND', 'MIC_PERMISSION_DENIED', 'AUDIO_INPUT_FAILED', 'AUDIO_OUTPUT_FAILED', 'WAKE_WORD_ERROR', 'VAD_ERROR', 'STT_ERROR', 'STT_TIMEOUT', 'LANGUAGE_UNKNOWN', 'LOW_CONFIDENCE', 'TTS_ERROR', 'TTS_TIMEOUT', 'CLOUD_PROVIDER_ERROR', 'VOICE_CANCELLED', 'SESSION_TIMEOUT', name='errorcategory'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'failure_category')
    op.drop_table('voice_sessions')
    # ### end Alembic commands ###
