"""phase 4: extend tasks and task_steps tables for agent orchestration

Revision ID: de808f46a925
Revises: 7a90f572da0d
Create Date: 2026-08-26 17:30:14.204688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de808f46a925'
down_revision: Union[str, None] = '7a90f572da0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('task_steps', sa.Column('intent', sa.JSON(), nullable=True))
    op.add_column('task_steps', sa.Column('arguments', sa.JSON(), nullable=False))
    op.add_column('task_steps', sa.Column('expected_outcome', sa.String(length=2000), nullable=True))
    op.add_column('task_steps', sa.Column('actual_result', sa.JSON(), nullable=True))
    op.add_column('task_steps', sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=True))
    op.add_column('task_steps', sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence'), nullable=True))
    op.add_column('task_steps', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('task_steps', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task_steps', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('task_steps', sa.Column('error', sa.JSON(), nullable=True))
    op.add_column('task_steps', sa.Column('observation_before', sa.JSON(), nullable=True))
    op.add_column('task_steps', sa.Column('observation_after', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('normalized_goal', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', name='taskpriority'), nullable=False))
    op.add_column('tasks', sa.Column('max_replans', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('current_step', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('total_steps', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'SENSITIVE', 'CRITICAL', name='risklevel'), nullable=True))
    op.add_column('tasks', sa.Column('requires_confirmation', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('failure_reason', sa.String(length=2000), nullable=True))
    op.add_column('tasks', sa.Column('result', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('extra_metadata', sa.JSON(), nullable=False))
    # Deliberately no op.create_foreign_key() for parent_task_id -> tasks.id:
    # SQLite cannot ALTER a table to add a constraint without batch mode
    # ("copy and move"), and a batch-mode rebuild of a table this size is
    # unnecessary risk for a nullable, self-referential column whose
    # integrity the ORM layer (SQLAlchemy's own ForeignKey()) already
    # models — see docs/phase-4/TASK-ENGINE.md.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_metadata')
    op.drop_column('tasks', 'result')
    op.drop_column('tasks', 'failure_reason')
    op.drop_column('tasks', 'requires_confirmation')
    op.drop_column('tasks', 'risk_level')
    op.drop_column('tasks', 'total_steps')
    op.drop_column('tasks', 'current_step')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'max_replans')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'normalized_goal')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('task_steps', 'observation_after')
    op.drop_column('task_steps', 'observation_before')
    op.drop_column('task_steps', 'error')
    op.drop_column('task_steps', 'retry_count')
    op.drop_column('task_steps', 'completed_at')
    op.drop_column('task_steps', 'started_at')
    op.drop_column('task_steps', 'confidence')
    op.drop_column('task_steps', 'risk_level')
    op.drop_column('task_steps', 'actual_result')
    op.drop_column('task_steps', 'expected_outcome')
    op.drop_column('task_steps', 'arguments')
    op.drop_column('task_steps', 'intent')
    op.drop_column('task_steps', 'description')
    # ### end Alembic commands ###
